INSERT INTO breed (name) VALUES ('Affenpinscher');
INSERT INTO breed (name) VALUES ('Afghan Hound');
INSERT INTO breed (name) VALUES ('Africanis');
INSERT INTO breed (name) VALUES ('Aidi');
INSERT INTO breed (name) VALUES ('Airedale Terrier');
INSERT INTO breed (name) VALUES ('Akbash');
INSERT INTO breed (name) VALUES ('Akita');
INSERT INTO breed (name) VALUES ('Aksaray Malaklisi');
INSERT INTO breed (name) VALUES ('Alano Español');
INSERT INTO breed (name) VALUES ('Alapaha Blue Blood Bulldog');
INSERT INTO breed (name) VALUES ('Alaskan Husky');
INSERT INTO breed (name) VALUES ('Alaskan Klee Kai');
INSERT INTO breed (name) VALUES ('Alaskan Malamute');
INSERT INTO breed (name) VALUES ('Alopekis');
INSERT INTO breed (name) VALUES ('Alpine Dachsbracke');
INSERT INTO breed (name) VALUES ('American Bulldog');
INSERT INTO breed (name) VALUES ('American Bully');
INSERT INTO breed (name) VALUES ('American Cocker Spaniel');
INSERT INTO breed (name) VALUES ('American English Coonhound');
INSERT INTO breed (name) VALUES ('American Eskimo Dog');
INSERT INTO breed (name) VALUES ('American Foxhound');
INSERT INTO breed (name) VALUES ('American Hairless Terrier');
INSERT INTO breed (name) VALUES ('American Leopard Hound');
INSERT INTO breed (name) VALUES ('American Pit Bull Terrier');
INSERT INTO breed (name) VALUES ('American Staffordshire Terrier');
INSERT INTO breed (name) VALUES ('American Water Spaniel');
INSERT INTO breed (name) VALUES ('Bắc Hà');
INSERT INTO breed (name) VALUES ('Bakharwal');
INSERT INTO breed (name) VALUES ('Banjara Hound');
INSERT INTO breed (name) VALUES ('Bankhar Dog');
INSERT INTO breed (name) VALUES ('Barak hound');
INSERT INTO breed (name) VALUES ('Barbado da Terceira');
INSERT INTO breed (name) VALUES ('Barbet');
INSERT INTO breed (name) VALUES ('Basenji');
INSERT INTO breed (name) VALUES ('Basque Shepherd Dog');
INSERT INTO breed (name) VALUES ('Basset Artésien Normand');
INSERT INTO breed (name) VALUES ('Basset Bleu de Gascogne');
INSERT INTO breed (name) VALUES ('Basset Fauve de Bretagne');
INSERT INTO breed (name) VALUES ('Basset Hound');
INSERT INTO breed (name) VALUES ('Bavarian Mountain Hound');
INSERT INTO breed (name) VALUES ('Beagle');
INSERT INTO breed (name) VALUES ('Beagle-Harrier');
INSERT INTO breed (name) VALUES ('Bearded Collie');
INSERT INTO breed (name) VALUES ('Beauceron');
INSERT INTO breed (name) VALUES ('Bedlington Terrier');
INSERT INTO breed (name) VALUES ('Belgian Shepherd');
INSERT INTO breed (name) VALUES ('Bergamasco Shepherd');
INSERT INTO breed (name) VALUES ('Berger Picard');
INSERT INTO breed (name) VALUES ('Bernese Mountain Dog');
INSERT INTO breed (name) VALUES ('Bichon Frisé');
INSERT INTO breed (name) VALUES ('Biewer Terrier');
INSERT INTO breed (name) VALUES ('Billy');
INSERT INTO breed (name) VALUES ('Ca Mè Mallorquí');
INSERT INTO breed (name) VALUES ('Ca de Bou');
INSERT INTO breed (name) VALUES ('Ca Rater Mallorquí');
INSERT INTO breed (name) VALUES ('Cairn Terrier');
INSERT INTO breed (name) VALUES ('Calupoh');
INSERT INTO breed (name) VALUES ('Campeiro Bulldog');
INSERT INTO breed (name) VALUES ('Can de Chira');
INSERT INTO breed (name) VALUES ('Can de Palleiro');
INSERT INTO breed (name) VALUES ('Canaan Dog');
INSERT INTO breed (name) VALUES ('Canadian Eskimo Dog');
INSERT INTO breed (name) VALUES ('Cane Corso');
INSERT INTO breed (name) VALUES ('Cane di Oropa');
INSERT INTO breed (name) VALUES ('Cane Paratore');
INSERT INTO breed (name) VALUES ('Cantabrian Water Dog');
INSERT INTO breed (name) VALUES ('Dachshund');
INSERT INTO breed (name) VALUES ('Dalmatian');
INSERT INTO breed (name) VALUES ('Dandie Dinmont Terrier');
INSERT INTO breed (name) VALUES ('Danish Spitz');
INSERT INTO breed (name) VALUES ('Danish–Swedish Farmdog');
INSERT INTO breed (name) VALUES ('Denmark Feist');
INSERT INTO breed (name) VALUES ('Dikkulak');
INSERT INTO breed (name) VALUES ('Dingo');
INSERT INTO breed (name) VALUES ('Dobermann');
INSERT INTO breed (name) VALUES ('Dogo Argentino');
INSERT INTO breed (name) VALUES ('Dogo Sardesco');
INSERT INTO breed (name) VALUES ('Dogue Brasileiro');
INSERT INTO breed (name) VALUES ('Dogue de Bordeaux');
INSERT INTO breed (name) VALUES ('Donggyeongi');
INSERT INTO breed (name) VALUES ('Drentse Patrijshond');
INSERT INTO breed (name) VALUES ('Drever');
INSERT INTO breed (name) VALUES ('Dunker');
INSERT INTO breed (name) VALUES ('English Cocker Spaniel');
INSERT INTO breed (name) VALUES ('English Foxhound');
INSERT INTO breed (name) VALUES ('English Mastiff');
INSERT INTO breed (name) VALUES ('English Setter');
INSERT INTO breed (name) VALUES ('English Shepherd');
INSERT INTO breed (name) VALUES ('Field Spaniel');
INSERT INTO breed (name) VALUES ('Fila Brasileiro');
INSERT INTO breed (name) VALUES ('Finnish Hound');
INSERT INTO breed (name) VALUES ('Finnish Lapphund');
INSERT INTO breed (name) VALUES ('Finnish Spitz');
INSERT INTO breed (name) VALUES ('Great Dane');
INSERT INTO breed (name) VALUES ('Greater Swiss Mountain Dog');
INSERT INTO breed (name) VALUES ('Greek Harehound');
INSERT INTO breed (name) VALUES ('Greek Shepherd');
INSERT INTO breed (name) VALUES ('Greenland Dog');
INSERT INTO breed (name) VALUES ('Greyhound');
INSERT INTO breed (name) VALUES ('Hällefors Elkhound');
INSERT INTO breed (name) VALUES ('Halden Hound');
INSERT INTO breed (name) VALUES ('Hamiltonstövare');
INSERT INTO breed (name) VALUES ('Hanover Hound');
INSERT INTO breed (name) VALUES ('Harrier');
INSERT INTO breed (name) VALUES ('Havanese');
INSERT INTO breed (name) VALUES ('Himalayan Sheepdog');
INSERT INTO breed (name) VALUES ('Hmong bobtail dog');
INSERT INTO breed (name) VALUES ('Hokkaido');
INSERT INTO breed (name) VALUES ('Hovawart');
INSERT INTO breed (name) VALUES ('Huntaway');
INSERT INTO breed (name) VALUES ('Ibizan Hound');
INSERT INTO breed (name) VALUES ('Icelandic Sheepdog');
INSERT INTO breed (name) VALUES ('Indian pariah dog');
INSERT INTO breed (name) VALUES ('Indian Spitz');
INSERT INTO breed (name) VALUES ('Irish Red and White Setter');
INSERT INTO breed (name) VALUES ('Irish Setter');
INSERT INTO breed (name) VALUES ('Irish Terrier');
INSERT INTO breed (name) VALUES ('Irish Water Spaniel');
INSERT INTO breed (name) VALUES ('Irish Wolfhound');
INSERT INTO breed (name) VALUES ('Istrian Coarse-haired Hound');
INSERT INTO breed (name) VALUES ('Istrian Shorthaired Hound');
INSERT INTO breed (name) VALUES ('Italian Greyhound');
INSERT INTO breed (name) VALUES ('Jack Russell Terrier');
INSERT INTO breed (name) VALUES ('Jagdterrier');
INSERT INTO breed (name) VALUES ('Jämthund');
INSERT INTO breed (name) VALUES ('Japanese Chin');
INSERT INTO breed (name) VALUES ('Japanese Spitz');
INSERT INTO breed (name) VALUES ('Japanese Terrier');
INSERT INTO breed (name) VALUES ('Jeju');
INSERT INTO breed (name) VALUES ('Jindo');
INSERT INTO breed (name) VALUES ('Jonangi');
INSERT INTO breed (name) VALUES ('Kai Ken');
INSERT INTO breed (name) VALUES ('Kaikadi');
INSERT INTO breed (name) VALUES ('Kamchatka Sled Dog');
INSERT INTO breed (name) VALUES ('Kangal Shepherd Dog');
INSERT INTO breed (name) VALUES ('Kanni');
INSERT INTO breed (name) VALUES ('Karakachan');
INSERT INTO breed (name) VALUES ('Karelian Bear Dog');
INSERT INTO breed (name) VALUES ('Karelo-Finnish Laika');
INSERT INTO breed (name) VALUES ('Labrador Retriever');
INSERT INTO breed (name) VALUES ('Lagotto Romagnolo');
INSERT INTO breed (name) VALUES ('Lài');
INSERT INTO breed (name) VALUES ('Lakeland Terrier');
INSERT INTO breed (name) VALUES ('Lancashire Heeler');
INSERT INTO breed (name) VALUES ('Landseer');
INSERT INTO breed (name) VALUES ('Mackenzie River Husky');
INSERT INTO breed (name) VALUES ('Magyar Agár');
INSERT INTO breed (name) VALUES ('Mahratta Hound');
INSERT INTO breed (name) VALUES ('Majorca Shepherd Dog');
INSERT INTO breed (name) VALUES ('Maltese');
INSERT INTO breed (name) VALUES ('Neapolitan Mastiff');
INSERT INTO breed (name) VALUES ('Nenets Herding Laika');
INSERT INTO breed (name) VALUES ('New Guinea singing dog');
INSERT INTO breed (name) VALUES ('New Zealand Heading Dog');
INSERT INTO breed (name) VALUES ('Newfoundland');
INSERT INTO breed (name) VALUES ('Norfolk Terrier');
INSERT INTO breed (name) VALUES ('Norrbottenspets');
INSERT INTO breed (name) VALUES ('Old Danish Pointer');
INSERT INTO breed (name) VALUES ('Old English Sheepdog');
INSERT INTO breed (name) VALUES ('Olde English Bulldogge');
INSERT INTO breed (name) VALUES ('Otterhound');
INSERT INTO breed (name) VALUES ('Pampas Deerhound');
INSERT INTO breed (name) VALUES ('Papillon');
INSERT INTO breed (name) VALUES ('Parson Russell Terrier');
INSERT INTO breed (name) VALUES ('Pastor Garafiano');
INSERT INTO breed (name) VALUES ('Rafeiro do Alentejo');
INSERT INTO breed (name) VALUES ('Rajapalayam');
INSERT INTO breed (name) VALUES ('Rampur Greyhound');
INSERT INTO breed (name) VALUES ('Rastreador Brasileiro');
INSERT INTO breed (name) VALUES ('Rat Terrier');
INSERT INTO breed (name) VALUES ('Ratonero Bodeguero Andaluz');
INSERT INTO breed (name) VALUES ('Saarloos wolfdog');
INSERT INTO breed (name) VALUES ('Sabueso Español');
INSERT INTO breed (name) VALUES ('Saint Miguel Cattle Dog');
INSERT INTO breed (name) VALUES ('Saint-Usuge Spaniel');
INSERT INTO breed (name) VALUES ('Sakhalin Husky');
INSERT INTO breed (name) VALUES ('Saluki');
INSERT INTO breed (name) VALUES ('Samoyed');
INSERT INTO breed (name) VALUES ('Taiwan Dog');
INSERT INTO breed (name) VALUES ('Tamaskan Dog');
INSERT INTO breed (name) VALUES ('Tang Dog');
INSERT INTO breed (name) VALUES ('Tarsus çatalburun');
INSERT INTO breed (name) VALUES ('Tatra Shepherd Dog');
INSERT INTO breed (name) VALUES ('Tazy');
INSERT INTO breed (name) VALUES ('Teddy Roosevelt Terrier');
INSERT INTO breed (name) VALUES ('Telomian');
INSERT INTO breed (name) VALUES ('Valencian Terrier');
INSERT INTO breed (name) VALUES ('Vikhan');
INSERT INTO breed (name) VALUES ('Villano de Las Encartaciones');
INSERT INTO breed (name) VALUES ('Villanuco de Las Encartaciones');
INSERT INTO breed (name) VALUES ('Vizsla');
INSERT INTO breed (name) VALUES ('Volkosob');
INSERT INTO breed (name) VALUES ('Volpino Italiano');
INSERT INTO breed (name) VALUES ('Weimaraner');
INSERT INTO breed (name) VALUES ('Welsh Hound');
INSERT INTO breed (name) VALUES ('Welsh Sheepdog');
INSERT INTO breed (name) VALUES ('Welsh Springer Spaniel');
INSERT INTO breed (name) VALUES ('Welsh Terrier');
INSERT INTO breed (name) VALUES ('West Country Harrier');
INSERT INTO breed (name) VALUES ('Xiasi Dog');
INSERT INTO breed (name) VALUES ('Xoloitzcuintle');
INSERT INTO breed (name) VALUES ('Yakutian Laika');
INSERT INTO breed (name) VALUES ('Yorkshire Terrier');
INSERT INTO breed (name) VALUES ('Zerdava');
